### ISSUE TITLE
No comments section

### ISSUE THREAD

**Issue by Ajax30** [StartBootstrap/startbootstrap-clean-blog#131]
I like this template and I was disappointed when I found there was no _comments section_ on the single post page. :(

**Comment by pandrey2003** [comment]
Upvote, a good idea!

**Comment by lameguest21** [comment]
You can always add disqus to your blog.

**Comment by davidtmiller** [comment]
Since this theme is meant to be used as a static blogging option, we're going to hold off on adding a comments section since I feel that it will be more often removed than used by most end users. Disqus is a great option for some comments on this theme (which I have utilized in the past).

To create a custom comments section, you can start with the Bootstrap form component and then go from there. A few buttons and static text to show previously left comments, perhaps housed within the card element, should work just fine for this purpose. Hopefully this helps!
